"""Site copy for tools/site/build.py.

Editorial rule: name no clients or projects; customer-journey examples are illustrative, not claims about results.
"""

SERVICES = [
    {
        "key": "web", "slug": "websites-branding", "icon": "web",
        "nav": "Websites & Branding",
        "blurb": "Positioning, websites and landing pages",
        "summary": "Clarify your story and create a digital experience built around the action you want visitors to take.",
        "link": "Explore Websites & Branding",
        "eyebrow": "Websites & Branding",
        "seo_title": "Website Design & Branding | Spark Media",
        "seo_desc": "Brand positioning, website design and landing pages that connect a compelling story to a clear next step.",
        "h1": "A better first impression. A clearer path forward.",
        "intro": "Your site should help people understand why you matter, trust what they see and know what to do next. We combine positioning, design, content and technology to make that possible.",
        "blocks": [
            ("Built around the decisions your customers make.",
             ["We start with the questions visitors bring to your site: Is this for me? Can they solve my problem? What happens if I reach out?",
              "Those answers guide the message, structure and design. From there, we build the forms, calls to action and system connections that turn an attractive site into a useful business asset."]),
        ],
        "help": ["Brand messaging and positioning", "Website strategy and design", "Landing pages", "Conversion-focused copy",
                 "Lead capture and booking flows", "SEO foundations", "Integration with your CRM and business tools"],
        "close_h2": "Make the website part of the workflow.",
        "close_body": "An inquiry shouldn’t end in an inbox nobody watches. We help connect your site to the people and systems responsible for the next step.",
        "cta": "Plan Your Website",
        "solutions": ["capture", "connect"],
    },
    {
        "key": "ai", "slug": "ai-agents-automation", "icon": "ai",
        "nav": "AI Agents & Automation",
        "blurb": "Voice, messaging and workflow automation",
        "summary": "Respond to inquiries, guide conversations and reduce repetitive work with AI and thoughtfully designed workflows.",
        "link": "Explore AI & Automation",
        "eyebrow": "AI Agents & Automation",
        "seo_title": "AI Agents & Business Automation | Spark Media",
        "seo_desc": "Practical AI voice, messaging and workflow automation to help your business respond faster and reduce manual work.",
        "h1": "Helpful conversations, even when your team is busy.",
        "intro": "A missed call or delayed response can turn a promising opportunity into a dead end. We design AI-assisted conversations and automations that help customers get answers, help your team get context and keep the next step moving.",
        "blocks": [
            ("AI with a job to do.",
             ["An AI agent can answer common questions, gather the details your team needs, route an inquiry or help someone book a time.",
              "Behind the conversation, workflows can update records, notify the right person and keep follow-up organized. Each implementation should reflect your business rules and include a clear way to hand off to a human."]),
        ],
        "help": ["AI voice agents", "Missed-call response", "Two-way SMS and email workflows", "Lead qualification",
                 "Appointment scheduling", "Lead reactivation", "Internal alerts and routing", "Workflow design and oversight"],
        "close_h2": "The best automation feels like good service.",
        "close_body": "We focus on the quality of the interaction, the accuracy of the information and the experience of the person on the other end.",
        "cta": "Explore an AI Use Case",
        "solutions": ["missed", "reactivate", "capture"],
    },
    {
        "key": "ads", "slug": "paid-media", "icon": "ads",
        "nav": "Paid Media",
        "blurb": "Google and Meta campaigns, tracked end to end",
        "summary": "Reach the right audience with Google and Meta campaigns connected to landing pages, follow-up and meaningful measurement.",
        "link": "Explore Paid Media",
        "eyebrow": "Paid Media",
        "seo_title": "Google & Meta Ads Management | Spark Media",
        "seo_desc": "Paid media strategy and management connected to landing pages, lead response and conversion tracking.",
        "h1": "Better campaigns start beyond the click.",
        "intro": "Getting attention is only the beginning. We connect paid advertising to the page, message and follow-up experience that comes after it.",
        "blocks": [
            ("Make every handoff count.",
             ["We develop campaigns around the people you’re trying to reach and the action you want them to take.",
              "Then we look at the full path: Does the landing page answer the right questions? Is the inquiry captured correctly? Who responds, and how quickly? What can the business learn from the outcome?"]),
        ],
        "help": ["Google Ads", "Meta Ads", "Retargeting", "Audience and offer strategy", "Landing-page alignment",
                 "Campaign creative testing", "Conversion tracking", "Reporting and optimization"],
        "close_h2": "See more than traffic and form fills.",
        "close_body": "We help you connect campaign activity to the conversations and opportunities that matter to your business.",
        "cta": "Talk About Advertising",
        "solutions": ["capture", "missed"],
    },
    {
        "key": "creative", "slug": "content-creative", "icon": "creative",
        "nav": "Content & Creative",
        "blurb": "Campaign creative, short-form video and UGC",
        "summary": "Make your message more compelling with campaign creative, content strategy, short-form video and UGC programs.",
        "link": "Explore Content & Creative",
        "eyebrow": "Content & Creative",
        "seo_title": "Content, Creative & UGC Strategy | Spark Media",
        "seo_desc": "Campaign creative, content and UGC strategy that make your message clear, credible and useful across channels.",
        "h1": "Creative that gives people a reason to care.",
        "intro": "Strong content shows what makes your business different in a way customers can feel and understand. We develop creative ideas and content systems that support your brand, your campaigns and the conversations you want to start.",
        "blocks": [
            ("The right message for the right moment.",
             ["Some audiences need a quick demonstration. Others need a detailed explanation, a customer perspective or a human face.",
              "We shape content around the questions people ask at each stage, then adapt it for your website, ads, social channels and follow-up."]),
        ],
        "help": ["Content strategy", "Copywriting", "Ad concepts and creative", "Short-form video strategy",
                 "UGC concepts and creator coordination", "Social content planning", "Creative testing"],
        "note": "Production may involve specialist collaborators depending on scope.",
        "close_h2": "Give your marketing something worth saying.",
        "close_body": "Tell us who you’re trying to reach and what they need to believe. We’ll help shape the ideas and the content system around them.",
        "cta": "Plan Your Creative",
        "extra_link": ("See our UGC and Instagram approach", "/social/"),
        "solutions": ["capture", "reactivate"],
    },
    {
        "key": "crm", "slug": "crm-sales-enablement", "icon": "crm",
        "nav": "CRM & Sales Enablement",
        "blurb": "Pipelines, routing and follow-up",
        "summary": "Give your team a clearer pipeline and a better way to qualify, follow up and book conversations.",
        "link": "Explore CRM & Sales",
        "eyebrow": "CRM & Sales Enablement",
        "seo_title": "CRM & Sales Enablement | Spark Media",
        "seo_desc": "CRM, pipeline and follow-up systems that help your team organize leads, book conversations and understand the sales journey.",
        "h1": "Give your sales process a better operating system.",
        "intro": "A new lead is only valuable if the right person sees it, understands it and knows what to do next. We help structure the information and workflows your team needs to move opportunities forward.",
        "blocks": [
            ("A clearer picture, from inquiry to outcome.",
             ["We map your stages, define useful handoffs and build follow-up around real buying behavior.",
              "Your team can see where a prospect came from, what they’ve asked, who owns the next action and where the opportunity stands."]),
        ],
        "help": ["CRM setup and architecture", "Pipeline design", "Lead routing and qualification", "Email and SMS nurturing",
                 "Appointment flows", "Database reactivation", "Sales tasks and alerts", "Practical reporting"],
        "close_h2": "Make it easier to follow through.",
        "close_body": "When everyone can see the next step, fewer opportunities go quiet. Let’s look at how your pipeline works today.",
        "cta": "Improve Your Sales Flow",
        "solutions": ["capture", "reactivate", "connect"],
    },
    {
        "key": "integration", "slug": "ai-consulting-integration", "icon": "integrate",
        "nav": "AI Consulting & Integration",
        "blurb": "Connect your software and find useful AI",
        "summary": "Find useful AI opportunities and help the software you rely on share information and trigger the right actions.",
        "link": "Explore Consulting & Integration",
        "eyebrow": "AI Consulting & Systems Integration",
        "seo_title": "AI Consulting & Systems Integration | Spark Media",
        "seo_desc": "Practical AI consulting and software integration for businesses with disconnected tools and manual workflows.",
        "h1": "Your tools should work together. Your people should have room to work.",
        "intro": "Many businesses have assembled a powerful software stack one purchase at a time. But when the systems don’t connect, staff become the integration. They re-enter data, chase status updates and work around information that lives in the wrong place.",
        "blocks": [
            ("We start by understanding how work actually moves.",
             ["We look at the systems you use, the information each one holds and the moments where work slows down.",
              "Then we recommend a practical path: connect existing platforms, redesign a workflow, build a useful dashboard, introduce an AI assistant or simplify a step altogether. The answer depends on the business, not on a preferred tool."]),
            ("A connected system is easier to run and easier to improve.",
             ["The aim is for information to reach the right place, for routine actions to happen reliably and for people to know when they need to step in.",
              "We design around the tools you own and the team that will use them."]),
        ],
        "help": ["Process mapping", "AI opportunity assessments", "CRM and software integrations", "Workflow automation",
                 "Operational dashboards", "AI-assisted internal processes", "Implementation planning and ongoing refinement"],
        "close_h2": "Let’s see how work moves through your business.",
        "close_body": "Bring a list of your tools and the steps that feel harder than they should. We’ll help you find where a connection would make the biggest difference.",
        "cta": "Let’s Map Your Systems",
        "solutions": ["connect", "capture"],
    },
]
for _s in SERVICES:
    _s["href"] = f'/services/{_s["slug"]}/'


SOLUTIONS = [
    {
        "key": "connect", "slug": "connect-your-systems", "icon": "connect",
        "nav": "Connect Your Systems",
        "blurb": "Get your software sharing the right information",
        "problem": "Our software doesn’t talk to each other.",
        "summary": "Connect the platforms and handoffs that keep your business moving.",
        "seo_title": "Connect Disconnected Business Software | Spark Media",
        "seo_desc": "Bring your CRM, website, scheduling, marketing and industry software into a more useful workflow.",
        "h1": "Make your software stack act like a team.",
        "intro": "Your company may run on ten, twenty or more platforms. Each one solves a particular problem, but the gaps between them create new ones. We help your tools exchange the right information so your team doesn’t have to carry it between systems by hand.",
        "blocks": [
            ("Where does the work get stuck?",
             ["A form submission doesn’t reach the sales team. A booked appointment isn’t visible in the CRM. A status change in one platform never triggers the next step. Reporting stops at the ad click because the outcome lives somewhere else.",
              "These are workflow problems, and they can often be solved without replacing the entire stack."]),
        ],
        "steps": ["Map the tools, owners and key handoffs.", "Identify the data and events each system needs.",
                  "Design integrations, alerts and human checkpoints.", "Test the real-world path and refine it as the business changes."],
        "outcome": "Fewer blind spots. Less copying and pasting. A clearer picture of what happens from first contact to completed work.",
        "cta": "Map My Workflow",
        "services": ["integration", "crm", "ai"],
    },
    {
        "key": "capture", "slug": "capture-convert-leads", "icon": "capture",
        "nav": "Capture & Convert Leads",
        "blurb": "Turn inquiries into real conversations",
        "problem": "We’re getting leads but losing momentum.",
        "summary": "Improve what happens between inquiry, qualification and the next conversation.",
        "seo_title": "Lead Capture & Conversion Systems | Spark Media",
        "seo_desc": "Connect campaigns, pages, CRM and follow-up to turn more inquiries into useful sales conversations.",
        "h1": "Don’t let the next opportunity stall after “submit.”",
        "intro": "A lead form isn’t the finish line. The experience that follows determines whether an interested person gets help, books a conversation or drifts away.",
        "blocks": [
            ("Build the path from interest to action.",
             ["We connect your advertising and website to a response process that fits the inquiry. That can include better forms, smarter routing, automated first responses, qualification, scheduling, reminders and clear ownership for your team.",
              "We also help you see where inquiries came from and what happened next."]),
        ],
        "components": ["Campaign and landing-page alignment", "Lead capture", "CRM integration", "Routing and qualification",
                       "Email and SMS follow-up", "Appointment booking", "Conversion reporting"],
        "cta": "Improve My Lead Flow",
        "services": ["ads", "web", "crm", "ai"],
    },
    {
        "key": "missed", "slug": "never-miss-an-opportunity", "icon": "phone",
        "nav": "Never Miss an Opportunity",
        "blurb": "A dependable first response, day or night",
        "problem": "We miss calls and respond too slowly.",
        "summary": "Create a more dependable first response with the right mix of AI, automation and human follow-through.",
        "seo_title": "Missed Call & Fast Lead Response Solutions | Spark Media",
        "seo_desc": "AI-assisted calls, messages and lead routing to help your business respond when customers are ready to talk.",
        "h1": "Be there when a customer is ready to talk.",
        "intro": "Calls come in after hours. Inquiries arrive while your team is with another customer. Good prospects don’t always try twice. We help you build a first-response experience that keeps the conversation moving.",
        "blocks": [
            ("A response that fits the situation.",
             ["Depending on your needs, that could mean an AI voice agent, a timely text, a helpful email, an alert to your team or a booking flow.",
              "The system should answer what it can, collect useful context and bring in a person when the conversation calls for one."]),
        ],
        "components": ["Missed-call follow-up", "AI call handling", "Lead intake and qualification", "Booking and reminders",
                       "Urgent inquiry routing", "Conversation logging and team alerts"],
        "cta": "Improve My Response Process",
        "services": ["ai", "crm", "integration"],
    },
    {
        "key": "reactivate", "slug": "reactivate-your-database", "icon": "reactivate",
        "nav": "Reactivate Your Database",
        "blurb": "Reconnect with past inquiries",
        "problem": "Our database is full of unfinished conversations.",
        "summary": "Reconnect with past inquiries through relevant, organized outreach.",
        "seo_title": "Lead Reactivation & Follow-Up | Spark Media",
        "seo_desc": "Reconnect with past inquiries using relevant outreach, organized conversations and clear next steps.",
        "h1": "Your next conversation may already be in your database.",
        "intro": "Many prospects weren’t ready when they first reached out. Others never got the follow-up they needed. We help you find sensible ways to reconnect, learn where interest stands and make it easy to take the next step.",
        "blocks": [
            ("Relevant outreach, with room for a real conversation.",
             ["We segment contacts around the context you have, develop appropriate messages and set up follow-up that responds to what people actually say.",
              "Interested replies move to your team or into a booking path. People who don’t want further contact are respected."]),
        ],
        "components": ["Contact segmentation", "Reactivation campaigns", "Two-way SMS and email", "Response categorization",
                       "Appointment routing", "CRM updates and reporting"],
        "cta": "Explore Reactivation",
        "services": ["crm", "ai", "creative"],
    },
]
for _s in SOLUTIONS:
    _s["href"] = f'/solutions/{_s["slug"]}/'


HOME = {
    "eyebrow": "Marketing + AI + Connected Systems",
    "h1": "Make every part of your business work together.",
    "body": "Your website creates an inquiry. Your ads bring in a lead. Your phone rings. Your team follows up. But when those steps live in separate tools, opportunities slip through the cracks. Spark Media brings marketing, AI and business automation together so your customer journey works as one connected system.",
    "intro_h2": "More software shouldn’t mean more friction.",
    "intro_body": [
        "Most growing companies already have the tools: a website, ad accounts, a CRM, scheduling software, email, texting, reporting and a stack of industry-specific platforms. The problem is that those tools often don’t share the right information at the right time. Teams copy data by hand, leads wait for a response and nobody has a clear picture of what’s working.",
        "We help you untangle the stack, connect the steps that matter and design better ways to work. Sometimes that means a stronger website or better advertising. Sometimes it’s an AI agent, a smarter follow-up process or an integration between the systems you already use. Usually, it’s the combination that moves the business forward.",
    ],
    "what_h2": "Creative thinking. Technical execution. One clear goal.",
    "cards": [
        {"icon": "web", "title": "Build your presence", "body": "Websites, brand positioning, landing pages and digital experiences that make it easy to understand your business and take the next step."},
        {"icon": "ads", "title": "Create demand", "body": "Google and Meta campaigns, content, creative and UGC strategy that bring the right people into the conversation."},
        {"icon": "ai", "title": "Convert opportunities", "body": "AI voice and messaging, lead qualification, CRM workflows, appointment scheduling and sales follow-up that help teams respond while interest is high."},
        {"icon": "integrate", "title": "Connect the business", "body": "Integrations, dashboards and practical AI implementations that reduce manual work and make information useful across your tools."},
    ],
    "connect_h2": "From first impression to real conversation.",
    "connect_body": [
        "Imagine someone clicks an ad, lands on a page built for their needs and requests a consultation. Their details flow into the right place. A fast, relevant response helps qualify the inquiry and offers a time to talk.",
        "That’s the kind of connected experience we build: useful for the customer, visible to your team and measurable for the business.",
    ],
    "journey": [
        ("click", "They click an ad", "A campaign reaches someone who needs what you offer."),
        ("web", "They land on a page built for them", "The message matches the ad and answers their first questions."),
        ("form", "They request a consultation", "Their details flow straight into the right place in your CRM."),
        ("ai", "A fast, relevant response", "An AI-assisted reply helps qualify the inquiry and offers a time to talk."),
        ("users", "Your team sees the full context", "Who they are, what they asked and where they came from."),
        ("reactivate", "Follow-up keeps going", "If they aren’t ready yet, the conversation doesn’t quietly end."),
        ("chart", "You see what started it", "Which campaign began the conversation and what happened after."),
    ],
    "stack_h2": "Twenty tools. One business. Let’s get them talking.",
    "stack_body": [
        "The goal isn’t to replace every platform you use. It’s to understand what each system does, where the handoffs fail and which connections will make the biggest difference.",
        "We map your workflows, clean up the flow of information and build automation around how your team actually works.",
    ],
    "tools": [
        ("Website forms", "on"), ("CRM", "on"), ("Google Ads", "on"), ("Meta Ads", ""), ("Phone system", "broken"),
        ("Scheduling", "on"), ("Email", ""), ("Texting", "broken"), ("Invoicing", ""), ("Reporting", "broken"),
        ("Spreadsheets", "broken"), ("Industry software", ""), ("Reviews", ""), ("Team chat", "on"), ("Payments", ""),
        ("Help desk", ""), ("AI assistant", "on"), ("Project management", ""),
    ],
    "approach_h2": "Start with the bottleneck. Build for the whole journey.",
    "steps": [
        ("Discover", "We learn how customers find you, how your team responds and which tools hold the critical information."),
        ("Design", "We prioritize the changes that can improve the customer experience and make work easier for your team."),
        ("Build", "We create the pages, campaigns, automations and connections that make the plan real."),
        ("Improve", "We look at what happens after launch, refine the system and help it evolve with your business."),
    ],
    "close_h2": "Tell us what’s slowing you down.",
    "close_body": "Whether you need a better website, more qualified demand or a way to make your software work together, we’ll help identify the next move.",
}

SERVICES_PAGE = {
    "h1": "Everything your growth system needs to work.",
    "intro": "Marketing generates attention. Your website turns attention into interest. Your team and systems turn that interest into customers. We work across those connections, bringing creative, technical and operational skills together around your goals.",
    "close_h2": "You don’t need all six services to get started.",
    "close_body": "We’ll begin with the problem you need to solve and bring in the right capabilities as the work calls for them.",
}

SOLUTIONS_PAGE = {
    "h1": "Start with the problem. Connect the right solution.",
    "intro": "You shouldn’t need to diagnose which service category your problem belongs in. Tell us what isn’t working. We’ll trace the customer and team experience, then build the pieces that solve it.",
}

INDUSTRIES_PAGE = {
    "h1": "Different businesses. Different buying journeys. Connected thinking.",
    "intro": "A venue inquiry, a local service call and a complex B2B sales conversation require different experiences. We adapt the message, channels and systems to the way your customers actually make decisions.",
    "items": [
        {"eyebrow": "Hospitality & venues", "title": "From first interest to tour or booking.",
         "body": "Help guests understand the experience, inquire with confidence and move smoothly from first interest to tour or booking. Websites, content, inquiry flows and coordinated follow-up can work together around the customer journey.",
         "tags": ["Inquiry flows", "Content & creative", "Tour and booking follow-up"],
         "img": "industry-hospitality.jpg", "alt": "A host welcomes guests into an event venue set with long tables and string lights"},
        {"eyebrow": "B2B & industrial", "title": "Explain complex capabilities clearly.",
         "body": "Support a longer buying cycle and create better handoffs between marketing and sales. We can connect positioning, website content, targeted campaigns and account-focused follow-up.",
         "tags": ["Positioning", "Targeted campaigns", "Marketing-to-sales handoffs"],
         "img": "industry-b2b.jpg", "alt": "Two colleagues review information on a tablet inside a modern manufacturing facility"},
        {"eyebrow": "Healthcare & wellness", "title": "Make the next step easy to find.",
         "body": "Make it easier for prospective patients or customers to find the right information, reach your team and understand the next step. Workflows should fit the sensitivity and requirements of the information involved.",
         "tags": ["Clear information", "Appointment flows", "Appropriate data handling"],
         "img": "industry-healthcare.jpg", "alt": "A staff member helps a client at the front desk of a bright wellness clinic"},
        {"eyebrow": "Local services", "title": "Turn high-intent moments into conversations.",
         "body": "Turn high-intent searches, calls and form fills into timely conversations. We help connect ads, local pages, lead response and scheduling.",
         "tags": ["Search ads", "Local pages", "Fast lead response", "Scheduling"],
         "img": "industry-local.jpg", "alt": "A home service technician holding a tablet smiles at a customer’s front door"},
    ],
    "close_h2": "Don’t see your industry?",
    "close_body": "If growth depends on a better customer journey and less friction between your tools, we should talk.",
}

ABOUT_PAGE = {
    "h1": "Marketing people and systems people, at the same table.",
    "intro": "Spark Media exists for businesses that need more than another campaign or another software subscription. We bring marketing strategy, creative execution and technical implementation together so each investment supports the next.",
    "principles": [
        ("We care about what happens after the click.",
         ["A compelling ad can start a conversation. A strong website can build confidence.",
          "But growth also depends on who responds, what information they have, how the customer is guided and whether the business can learn from the outcome. We work across that full experience."]),
        ("Practical AI, built around people.",
         ["We look for places where technology can make service more responsive and work more manageable.",
          "That means understanding the job first, choosing tools for a reason and making sure your team remains in control of the process."]),
        ("Built to fit your business.",
         ["Your workflows, customers and existing platforms shape the solution. We aim to make the systems you rely on more useful and give your team a clearer view of what happens next.",
          "Your business should have appropriate access to and ownership of its client-facing assets, accounts and data, as defined in the project agreement."]),
    ],
    "founder": "Spark Media is led by founder Dave McCormick. If you’d like to talk through your goals directly, you can reach Dave at dave@sparkmedia.ai.",
}

CONTACT_PAGE = {
    "h1": "Let’s find the next move that matters.",
    "intro": "Tell us what you’re trying to improve. A clearer website? Better lead flow? Faster responses? A software stack that finally works together? We’ll start with a conversation about the goal and the obstacles in the way.",
    "topics": ["Website & Branding", "Advertising", "AI & Automation", "CRM & Sales", "Systems Integration", "Not sure yet? That’s fine too."],
}
